---
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/app
    steps:
      - checkout
      - run: 
          name: pipenv install
          command: sudo pipenv install --system
      - run: 
          name: git config
          command: |
            git config --global user.email "knqyf263@gmail.com"
            git config --global user.name "Teppei Fukuda"
      - run: 
          name: run
          command: python update.py
workflows:
  version: 2
  schedule_workflow:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "31 * * * *"
          filters:
            branches:
              only:
                - master
